# Generated by Django 3.1.2 on 2020-11-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicartapp', '0002_auto_20201119_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
